configdb/config/routes.rb
Rails.application.routes.draw do
  resources :peers

  resources :autnums

  resources :ipv6s

  resources :ipv4s

  resources :gigabit_ethernets

  resources :devices do
    namespace :status do
      get :platform, to: 'devices#platform'
    end
  end

end

configdb/app/models/gigabit_ethernet.rb
class GigabitEthernet < ActiveRecord::Base
  belongs_to :device

  # FIXME: Migrate into app/decorators along with active_decorator gem
  def name_with_device
    "#{device.name} - #{name}"
  end
end

configdb/app/controllers/gigabit_ethernets_controller.rb
class GigabitEthernetsController < ApplicationController
  before_action :set_gigabit_ethernet, only: [:show, :edit, :update, :destroy]

  # GET /gigabit_ethernets
  # GET /gigabit_ethernets.json
  def index
    @gigabit_ethernets = GigabitEthernetCondition.new(search_params).gigabit_ethernets
  end

  # GET /gigabit_ethernets/1
  # GET /gigabit_ethernets/1.json
  def show
  end

  # GET /gigabit_ethernets/new
  def new
    @gigabit_ethernet = GigabitEthernet.new
  end

  # GET /gigabit_ethernets/1/edit
  def edit
  end

  # POST /gigabit_ethernets
  # POST /gigabit_ethernets.json
  def create
    @gigabit_ethernet = GigabitEthernet.new(gigabit_ethernet_params)

    respond_to do |format|
      if @gigabit_ethernet.save
        format.html { redirect_to @gigabit_ethernet, notice: 'Gigabit ethernet was successfully created.' }
        format.json { render :show, status: :created, location: @gigabit_ethernet }
      else
        format.html { render :new }
        format.json { render json: @gigabit_ethernet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigabit_ethernets/1
  # PATCH/PUT /gigabit_ethernets/1.json
  def update
    respond_to do |format|
      if @gigabit_ethernet.update(gigabit_ethernet_params)
        format.html { redirect_to @gigabit_ethernet, notice: 'Gigabit ethernet was successfully updated.' }
        format.json { render :show, status: :ok, location: @gigabit_ethernet }
      else
        format.html { render :edit }
        format.json { render json: @gigabit_ethernet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigabit_ethernets/1
  # DELETE /gigabit_ethernets/1.json
  def destroy
    @gigabit_ethernet.destroy
    respond_to do |format|
      format.html { redirect_to gigabit_ethernets_url, notice: 'Gigabit ethernet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gigabit_ethernet
      @gigabit_ethernet = GigabitEthernet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gigabit_ethernet_params
      params.require(:gigabit_ethernet).permit(:device_id, :name, :description, :speed)
    end

    def search_params
      params.permit(:device_id, :name)
    end
end

configdb/app/helpers/gigabit_ethernets_helper.rb
module GigabitEthernetsHelper
end

configdb/app/views/gigabit_ethernets/_form.html.erb
<%= form_for @gigabit_ethernet, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :device_id, :class => 'control-label' %>
    <%= f.collection_select :device_id, Device.all, :id, :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <%= f.text_area :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label' %>
    <%= f.text_area :description, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :speed, :class => 'control-label' %>
    <%= f.text_area :speed, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                gigabit_ethernets_path, :class => 'btn' %>
  </div>
<% end %>

configdb/app/views/gigabit_ethernets/edit.html.erb
<%- model_class = GigabitEthernet -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

configdb/app/views/gigabit_ethernets/index.html.erb
<%- model_class = GigabitEthernet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:device) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:speed) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gigabit_ethernets.each do |gigabit_ethernet| %>
      <tr>
        <td><%= link_to gigabit_ethernet.id, gigabit_ethernet_path(gigabit_ethernet) %></td>
        <td><%= gigabit_ethernet.device.name %></td>
        <td><%= gigabit_ethernet.name %></td>
        <td><%= gigabit_ethernet.description %></td>
        <td><%= gigabit_ethernet.speed %></td>
        <td><%=l gigabit_ethernet.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_gigabit_ethernet_path(gigabit_ethernet), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      gigabit_ethernet_path(gigabit_ethernet),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_gigabit_ethernet_path,
            :class => 'btn btn-primary' %>

configdb/app/views/gigabit_ethernets/new.html.erb
<%- model_class = GigabitEthernet -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

configdb/app/views/gigabit_ethernets/show.html.erb
<%- model_class = GigabitEthernet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:device) %>:</strong></dt>
  <dd><%= @gigabit_ethernet.device.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @gigabit_ethernet.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @gigabit_ethernet.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:speed) %>:</strong></dt>
  <dd><%= @gigabit_ethernet.speed %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              gigabit_ethernets_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_gigabit_ethernet_path(@gigabit_ethernet), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              gigabit_ethernet_path(@gigabit_ethernet),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>