configdb/config/routes.rb
Rails.application.routes.draw do
  resources :peers

  resources :autnums

  resources :ipv6s

  resources :ipv4s

  resources :gigabit_ethernets

  resources :devices do
    namespace :status do
      get :platform, to: 'devices#platform'
    end
  end

end

configdb/app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :autnum

  def cli
    model = "Cli::#{platform.classify}".safe_constantize
    @_cli ||= model.new(self)
  end
end

configdb/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = DeviceCondition.new(search_params).devices
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:autnum_id, :name, :fqdn, :platform)
    end

    def search_params
      params.permit(:name)
    end
end

configdb/app/controllers/status/devices_controller.rb
module Status
  class DevicesController < ApplicationController
    before_action :set_device, only: [:platform]

    def platform
      render json: @device.cli.platform
    end

    private
      def set_device
        @device = Device.find(params[:device_id])
      end
  end
end

configdb/app/helpers/devices_helper.rb
module DevicesHelper
end

configdb/app/views/devices/_form.html.erb
<%= form_for @device, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :autnum_id, :class => 'control-label' %>
    <%= f.collection_select :autnum_id, Autnum.all, :id, :asn, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <%= f.text_area :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :fqdn, :class => 'control-label' %>
    <%= f.text_area :fqdn, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :platform, :class => 'control-label' %>
    <%= f.text_area :platform, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                devices_path, :class => 'btn' %>
  </div>
<% end %>

configdb/app/views/devices/edit.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

configdb/app/views/devices/index.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:asn) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:fqdn) %></th>
      <th><%= model_class.human_attribute_name(:platform) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to device.id, device_path(device) %></td>
        <td><%= device.name %></td>
        <td><%= device.autnum.asn %></td>
        <td><%= device.fqdn %></td>
        <td><%= device.platform %></td>
        <td><%=l device.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_device_path(device), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      device_path(device),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

configdb/app/views/devices/new.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

configdb/app/views/devices/show.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:asn) %>:</strong></dt>
  <dd><%= @device.autnum.asn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @device.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fqdn) %>:</strong></dt>
  <dd><%= @device.fqdn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:platform) %>:</strong></dt>
  <dd><%= @device.platform %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              devices_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_device_path(@device), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              device_path(@device),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>