configdb/config/routes.rb
Rails.application.routes.draw do
  resources :peers

  resources :autnums

  resources :ipv6s

  resources :ipv4s

  resources :gigabit_ethernets

  resources :devices do
    namespace :status do
      get :platform, to: 'devices#platform'
    end
  end

end

configdb/app/models/autnum.rb
class Autnum < ActiveRecord::Base
end

configdb/app/controllers/autnums_controller.rb
class AutnumsController < ApplicationController
  before_action :set_autnum, only: [:show, :edit, :update, :destroy]

  # GET /autnums
  # GET /autnums.json
  def index
    @autnums = Autnum.all
  end

  # GET /autnums/1
  # GET /autnums/1.json
  def show
  end

  # GET /autnums/new
  def new
    @autnum = Autnum.new
  end

  # GET /autnums/1/edit
  def edit
  end

  # POST /autnums
  # POST /autnums.json
  def create
    @autnum = Autnum.new(autnum_params)

    respond_to do |format|
      if @autnum.save
        format.html { redirect_to @autnum, notice: 'Autnum was successfully created.' }
        format.json { render :show, status: :created, location: @autnum }
      else
        format.html { render :new }
        format.json { render json: @autnum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autnums/1
  # PATCH/PUT /autnums/1.json
  def update
    respond_to do |format|
      if @autnum.update(autnum_params)
        format.html { redirect_to @autnum, notice: 'Autnum was successfully updated.' }
        format.json { render :show, status: :ok, location: @autnum }
      else
        format.html { render :edit }
        format.json { render json: @autnum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autnums/1
  # DELETE /autnums/1.json
  def destroy
    @autnum.destroy
    respond_to do |format|
      format.html { redirect_to autnums_url, notice: 'Autnum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autnum
      @autnum = Autnum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def autnum_params
      params.require(:autnum).permit(:asn, :name)
    end
end

configdb/app/helpers/autnums_helper.rb
module AutnumsHelper
end

configdb/app/views/autnums/_form.html.erb
<%= form_for @autnum, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :asn, :class => 'control-label' %>
    <%= f.number_field :asn, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <%= f.text_area :name, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                autnums_path, :class => 'btn' %>
  </div>
<% end %>

configdb/app/views/autnums/edit.html.erb
<%- model_class = Autnum -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

configdb/app/views/autnums/index.html.erb
<%- model_class = Autnum -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:asn) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @autnums.each do |autnum| %>
      <tr>
        <td><%= link_to autnum.id, autnum_path(autnum) %></td>
        <td><%= autnum.asn %></td>
        <td><%= autnum.name %></td>
        <td><%=l autnum.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_autnum_path(autnum), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      autnum_path(autnum),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_autnum_path,
            :class => 'btn btn-primary' %>

configdb/app/views/autnums/new.html.erb
<%- model_class = Autnum -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

configdb/app/views/autnums/show.html.erb
<%- model_class = Autnum -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:asn) %>:</strong></dt>
  <dd><%= @autnum.asn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @autnum.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              autnums_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_autnum_path(@autnum), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              autnum_path(@autnum),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>