configdb/config/routes.rb
Rails.application.routes.draw do
  resources :peers

  resources :autnums

  resources :ipv6s

  resources :ipv4s

  resources :gigabit_ethernets

  resources :devices do
    namespace :status do
      get :platform, to: 'devices#platform'
    end
  end

end

configdb/app/models/peer.rb
class Peer < ActiveRecord::Base
  belongs_to :device
  belongs_to :autnum
end

configdb/app/controllers/peers_controller.rb
class PeersController < ApplicationController
  before_action :set_peer, only: [:show, :edit, :update, :destroy]

  # GET /peers
  # GET /peers.json
  def index
    @peers = Peer.all
  end

  # GET /peers/1
  # GET /peers/1.json
  def show
  end

  # GET /peers/new
  def new
    @peer = Peer.new
  end

  # GET /peers/1/edit
  def edit
  end

  # POST /peers
  # POST /peers.json
  def create
    @peer = Peer.new(peer_params)

    respond_to do |format|
      if @peer.save
        format.html { redirect_to @peer, notice: 'Peer was successfully created.' }
        format.json { render :show, status: :created, location: @peer }
      else
        format.html { render :new }
        format.json { render json: @peer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peers/1
  # PATCH/PUT /peers/1.json
  def update
    respond_to do |format|
      if @peer.update(peer_params)
        format.html { redirect_to @peer, notice: 'Peer was successfully updated.' }
        format.json { render :show, status: :ok, location: @peer }
      else
        format.html { render :edit }
        format.json { render json: @peer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peers/1
  # DELETE /peers/1.json
  def destroy
    @peer.destroy
    respond_to do |format|
      format.html { redirect_to peers_url, notice: 'Peer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peer
      @peer = Peer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peer_params
      params.require(:peer).permit(:device_id, :autnum_id, :neighbor)
    end
end

configdb/app/helpers/peers_helper.rb
module PeersHelper
end

configdb/app/views/peers/_form.html.erb
<%= form_for @peer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :device_id, :class => 'control-label' %>
    <%= f.collection_select :device_id, Device.all, :id, :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :autnum_id, :class => 'control-label' %>
    <%= f.collection_select :autnum_id, Autnum.all, :id, :asn, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :neighbor, :class => 'control-label' %>
    <%= f.text_area :neighbor, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                peers_path, :class => 'btn' %>
  </div>
<% end %>

configdb/app/views/peers/edit.html.erb
<%- model_class = Peer -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

configdb/app/views/peers/index.html.erb
<%- model_class = Peer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:device) %></th>
      <th><%= model_class.human_attribute_name(:asn) %></th>
      <th><%= model_class.human_attribute_name(:neighbor) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @peers.each do |peer| %>
      <tr>
        <td><%= link_to peer.id, peer_path(peer) %></td>
        <td><%= peer.device.name %></td>
        <td><%= peer.autnum.asn %></td>
        <td><%= peer.neighbor %></td>
        <td><%=l peer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_peer_path(peer), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      peer_path(peer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_peer_path,
            :class => 'btn btn-primary' %>

configdb/app/views/peers/new.html.erb
<%- model_class = Peer -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

configdb/app/views/peers/show.html.erb
<%- model_class = Peer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:device) %>:</strong></dt>
  <dd><%= @peer.device.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:asn) %>:</strong></dt>
  <dd><%= @peer.autnum.asn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighbor) %>:</strong></dt>
  <dd><%= @peer.neighbor %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              peers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_peer_path(@peer), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              peer_path(@peer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>